# Generated by Django 5.2 on 2025-05-06 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
